use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let ps1_path = Path::new(&manifest_dir).join("scripts").join("install.ps1");
    let cmd_path = Path::new(&manifest_dir).join("scripts").join("install.cmd");

    let ps1_content = std::fs::read(&ps1_path).expect("Failed to read scripts/install.ps1");

    let mut ps1_with_bom = Vec::new();
    ps1_with_bom.extend_from_slice(&[0xEF, 0xBB, 0xBF]);
    ps1_with_bom.extend_from_slice(&ps1_content);

    use base64::Engine;
    let b64 = base64::engine::general_purpose::STANDARD.encode(&ps1_with_bom);

    let mut lines = Vec::new();
    for chunk in b64.as_bytes().chunks(76) {
        lines.push(std::str::from_utf8(chunk).unwrap());
    }
    let b64_block = lines.join("\r\n");

    let cmd_content = format!(
        "@echo off\r\n\
         REM rgytui installer for Windows\r\n\
         REM\r\n\
         REM This file is auto-generated by build.rs from scripts/install.ps1.\r\n\
         REM Do not edit manually — edit install.ps1 and rebuild.\r\n\
         REM\r\n\
         setlocal\r\n\
         set \"TMPFILE=%TEMP%\\rgytui-install.ps1\"\r\n\
         set \"B64FILE=%TEMP%\\rgytui-install.b64\"\r\n\
         \r\n\
         REM Extract Base64 between markers\r\n\
         powershell -NoProfile -Command ^\r\n\
         \"$c=Get-Content '%~f0' -Raw;\" ^\r\n\
         \"$m=[regex]::Match($c,'__BEGIN_SCRIPT__\\r?\\n(.*)\\r?\\n__END_SCRIPT__','Singleline');\" ^\r\n\
         \"[System.IO.File]::WriteAllText('%B64FILE%',$m.Groups[1].Value.Trim())\"\r\n\
         \r\n\
         REM Decode Base64 -> PowerShell script\r\n\
         certutil -decode \"%B64FILE%\" \"%TMPFILE%\" >nul 2>&1\r\n\
         if %errorlevel% neq 0 (\r\n\
         echo Failed to decode installer script. The download may be corrupted.\r\n\
         echo Try downloading again.\r\n\
         pause\r\n\
         exit /b 1\r\n\
         )\r\n\
         \r\n\
         REM Run the installer\r\n\
         powershell -NoProfile -ExecutionPolicy RemoteSigned -File \"%TMPFILE%\"\r\n\
         set \"EXIT_CODE=%errorlevel%\"\r\n\
         \r\n\
         REM Cleanup temp files\r\n\
         del \"%B64FILE%\" >nul 2>&1\r\n\
         del \"%TMPFILE%\" >nul 2>&1\r\n\
         \r\n\
         if %EXIT_CODE% neq 0 (\r\n\
         echo.\r\n\
         echo The installer encountered an error. Check the output above.\r\n\
         pause\r\n\
         exit /b 1\r\n\
         )\r\n\
         \r\n\
         __BEGIN_SCRIPT__\r\n\
         {b64_block}\r\n\
         __END_SCRIPT__\r\n"
    );

    std::fs::write(&cmd_path, cmd_content).expect("Failed to write scripts/install.cmd");

    println!("cargo::rerun-if-changed=scripts/install.ps1");
}
